### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by ushiodas** [scribenet/scml_dtds#13]
checking who continues to watch this

**Comment by andrewhthomas** [comment]
I still get notifications on this.

**Comment by ushiodas** [comment]
Okay, cool. So do we need to change anything here with the GitHub stuff
(given that you and Noah are the only "Scribe technologies" people left)?
Did Dan and any others already remove themselves without incident? Does
Noah need additional access? [not urgent, I imagine..]

Steven S. Ushioda
Publishing Services Specialist
Scribe Inc.

www.scribenet.com
main telephone: 215.336.5094 x133
direct telephone: 267.234.7126

842 South Second Street, Philadelphia, PA 19147
